name: offline_voice_typing
description: Offline voice typing for Persian and English with system IME.
publish_to: 'none'
version: 0.5.0+7

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  permission_handler: ^10.4.5
  archive: ^3.6.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  vosk_flutter: ^0.3.48
  android_intent_plus: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  permission_handler: ^10.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/models/
